spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    gateway:
      server:
        webflux:
          # Global CORS configuration
          routes:
            # Route all auth service traffic to user service
            - id: auth-service-route
              uri: http://localhost:8081 # User service port
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=0

            # User service routes (for non-auth endpoints if any)
            - id: user-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=0

            # Project service routes
            - id: project-service-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/projects/**
              filters:
                - StripPrefix=0

            # Notification service routes
            - id: notification-service-route
              uri: http://localhost:8084
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=0

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

# Server configuration
server:
  port: ${SERVER_PORT:8080}

# RSA JWT Configuration (for validating tokens from auth service)
rsa:
  public:
    key: ${RSA_PUBLIC_KEY}

# Legacy JWT config (kept for compatibility)
jwt:
  secret: ${JWT_SECRET:myVerySecureJwtSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.midlane.project_management_tool_api_gateway: ${LOG_LEVEL_GATEWAY:DEBUG}
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE:health,info}
  endpoint:
    health:
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:always}
