spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route all auth service traffic to user service
            - id: auth-service-route
              uri: ${USER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=0

            # User service routes (for non-auth endpoints if any)
            - id: user-service-route
              uri: ${USER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=0

            # Project service routes
            - id: project-service-route
              uri: ${PROJECT_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/projects/**
              filters:
                - StripPrefix=0

            # Notification service routes (when implemented)
            - id: notification-service-route
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=0
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "${FRONTEND_URL:http://localhost:3000}"
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

server:
  port: ${SERVER_PORT:8080}

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
